server {
    listen 8080;  # 내부 모니터링용 포트
    server_name localhost;

    location /stub_status {
        stub_status;
        allow 127.0.0.1;   # 로컬(컨테이너 내부/호스트)에서만 접근 허용
        allow 10.0.0.0/18; # VPC 내부 IP 대역 허용
        deny all;          # 외부 접근 차단
    }
}