server {
    listen 8080 default_server;  # 내부 모니터링용 포트
    server_name localhost;

    location /stub_status {
        stub_status;         # 상태정보 출력 활성화
        access_log off;      # 모니터링 로그는 쌓지 않음 (디스크 절약)
        allow 127.0.0.1;     # 컨테이너 내부 접근 허용
        allow 10.0.0.0/18;   # AWS VPC 내부(Private IP) 접근 허용
        allow 172.16.0.0/12; # Docker 네트워크 대역 접근 허용
        deny all;            # 그 외 외부 접근 차단
    }
}